"use client";

/**
 * IC42N Anchor client (browser)
 *
 * Purpose:
 * - Create an AnchorProvider from wallet-adapter (Phantom/Solflare/Backpack/etc.)
 * - Create a typed Program<Ic42n>
 * - Provide an IDL-based accounts coder (BorshAccountsCoder) for read-only decoding
 *
 * Notes:
 * - This is browser-safe: no NodeWallet, no Keypair payer.
 * - Program constructor in your Anchor version is: new Program(idl, provider)
 * - IDL decoding does NOT require a wallet connection.
 */

import { useMemo } from "react";
import { AnchorProvider, BorshAccountsCoder, Program } from "@coral-xyz/anchor";
import type { Idl } from "@coral-xyz/anchor";
import { PublicKey, Transaction, VersionedTransaction } from "@solana/web3.js";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";

import IDL_JSON from "@/solana/anchor/idl/ic42n.json";
import type { Ic42n } from "@/solana/anchor/types/ic42n";

// ────────────────────────────────────────────────────────────────
// 1) Types / exports
// ────────────────────────────────────────────────────────────────

export type { Ic42n };
export type Ic42nProgram = Program<Ic42n>;

type AnyTx = Transaction | VersionedTransaction;

/**
 * The minimal wallet shape AnchorProvider needs in the browser.
 * (No payer Keypair — wallet-adapter provides signing methods.)
 */
type AnchorBrowserWallet = {
  publicKey: PublicKey;
  signTransaction<T extends AnyTx>(tx: T): Promise<T>;
  signAllTransactions<T extends AnyTx>(txs: T[]): Promise<T[]>;
};

// ────────────────────────────────────────────────────────────────
// 2) IDL + Program ID helpers
// ────────────────────────────────────────────────────────────────

/**
 * Typed IDL view (Anchor expects the generic Idl shape for coders).
 * We keep both:
 * - IC42N_IDL: for account decoding
 * - Ic42n IDL cast: for Program<Ic42n> typing
 */
export const IC42N_IDL = IDL_JSON as unknown as Idl;

/**
 * Program ID pulled from the IDL "address" field (as generated by Anchor).
 * Useful for PDA derivation / debugging / explorers, even if Program() doesn't need it.
 */
const { address } = IDL_JSON as unknown as { address: string };
export const PROGRAM_ID = new PublicKey(address);

/**
 * Read-only 'accounts' coder.
 * Use this anywhere you have accountInfo.data and want decoded fields:
 *   IC42N_ACCOUNTS_CODER.decode("config", accountInfo.data)
 *
 * IMPORTANT: account name string must match IDL account name exactly.
 */
export const IC42N_ACCOUNTS_CODER = new BorshAccountsCoder(IC42N_IDL);

// ────────────────────────────────────────────────────────────────
// 3) Provider hook (wallet-adapter -> AnchorProvider)
// ────────────────────────────────────────────────────────────────

export function useAnchorProvider(): AnchorProvider | null {
  const { connection } = useConnection();
  const { publicKey, connected, signTransaction, signAllTransactions } =
    useWallet();

  return useMemo(() => {
    // Anchor requires a signer-capable wallet (not just a pubkey).
    if (!connected || !publicKey || !signTransaction) return null;

    // Ensure signAllTransactions exists even if a wallet doesn't implement it.
    const wallet: AnchorBrowserWallet = {
      publicKey,
      signTransaction,
      signAllTransactions:
        signAllTransactions ??
        (async (txs) => Promise.all(txs.map((tx) => signTransaction(tx)))),
    };

    return new AnchorProvider(connection, wallet, {
      commitment: "confirmed",
      preflightCommitment: "confirmed",
    });
  }, [connection, connected, publicKey, signTransaction, signAllTransactions]);
}

// ────────────────────────────────────────────────────────────────
// 4) Program hook (typed Program<Ic42n>)
// ────────────────────────────────────────────────────────────────

export function useProgram(): Ic42nProgram | null {
  const provider = useAnchorProvider();

  return useMemo(() => {
    if (!provider) return null;

    // In your Anchor client version: Program constructor is (idl, provider)
    return new Program<Ic42n>(IDL_JSON as unknown as Ic42n, provider);
  }, [provider]);
}